import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.css';
import { Poppins, Roboto } from 'next/font/google';

const poppins = Poppins({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata = {
  title: 'Newspress',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${roboto.className}`}>
        <Navbar />
        <main className='flex h-[100dvh]'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
